<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="rover">

  <xacro:property name="base_width" value="0.7357" />
  <xacro:property name="base_len" value="1.0" />
  <xacro:property name="base_height" value="0.6" />
  <xacro:property name="wheel_radius" value="0.035" />
  <xacro:property name="base_wheel_gap" value="0.007" />
  <xacro:property name="wheel_separation" value="0.15" />
  <xacro:property name="wheel_joint_offset" value="0.02" />

  <xacro:property name="caster_wheel_radius" value="${wheel_radius/2}" />
  <xacro:property name="caster_wheel_mass" value="0.001" />
  <xacro:property name="caster_wheel_joint_offset" value="-0.052" />
  <!-- <xacro:property name="mesh_scale" value="0.0254 0.0254 0.0254" /> -->
  <xacro:property name="PI" value="3.141592" />

  <!--Color Properties-->
  <material name="blue">
    <color rgba="0 0 0.8 1" />
  </material>
  <material name="black">
    <color rgba="0 0 0 1" />
  </material>
  <material name="white">
    <color rgba="1 1 1 1" />
  </material>
  <material name="red">
    <color rgba="0.8 0.0 0.0 1.0" />
  </material>

  <!--Interial macros-->
  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertial>
      <mass value="${m}" />
      <inertia ixx="${m*(3*r*r+h*h)/12}" ixy="0" ixz="0" iyy="${m*(3*r*r+h*h)/12}" iyz="0" izz="${m*r*r/2}" />
    </inertial>
  </xacro:macro>

  <xacro:macro name="box_inertia" params="m w h d">
    <inertial>
      <mass value="${m}" />
      <inertia ixx="${m / 12.0 * (d*d + h*h)}" ixy="0.0" ixz="0.0" iyy="${m / 12.0 * (w*w + h*h)}" iyz="0.0" izz="${m / 12.0 * (w*w + d*d)}" />
    </inertial>
  </xacro:macro>

  <xacro:macro name="sphere_inertia" params="m r">
    <inertial>
      <mass value="${m}" />
      <inertia ixx="${2.0*m*(r*r)/5.0}" ixy="0.0" ixz="0.0" iyy="${2.0*m*(r*r)/5.0}" iyz="0.0" izz="${2.0*m*(r*r)/5.0}" />
    </inertial>
  </xacro:macro>

  <!--Base Footprint-->
  <link name="base_footprint">
    <xacro:box_inertia m="10" w="0.001" h="0.001" d="0.001" />
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.001 0.001 0.001" />
      </geometry>
    </visual>
  </link>

  <!--Base link-->
  <link name="base_link">
    <xacro:box_inertia m="45.0" w="${base_len}" h="${base_width}" d="${base_height}" />
    <visual>
      <origin rpy="0 0 0" xyz="-0.25 0.0 0.2"/>
      <geometry>
        <mesh filename="package://mrover/rover_description/meshes/rover.stl" scale="1 1 1"/>
      </geometry>
      <material name="blue" />
    </visual>
    <collision>
      <geometry>
        <box size="${base_len} ${base_width} ${base_height}" />
      </geometry>
    </collision>
  </link>


  <!--base_link to base_footprint Joint-->
  <joint name="base_link_joint" type="fixed">
    <origin xyz="0 0 ${wheel_radius + 0.005}" rpy="0 0 0" />
    <parent link="base_footprint" />
    <child link="base_link" />
  </joint>


  <xacro:include filename="$(find mrover)/rover_description/rover_gazebo_plugins.xacro" />

</robot>